### ISSUE TITLE
Issues posting text, video and images into the profile page of a new user, via a form. 

### ISSUE THREAD

**Issue by andresv2** [andresv2/futbook#1]
```
#<ArgumentError: wrong number of arguments (4 for 3)>
sinatra.route   
POST /players
```

```
server file
post('/players/?:id?') do
      create_member(
        params["name"],
        params["last_name"],
        params["email"],
         params["picture"],
        )


databasehelper file
 def create_member(name, last_name, email, picture="")
      @id = $redis.incr("entry_id")

      $redis.hmset(
        "entry:#{@id}",

        "name",     name,
        "last_name", last_name,
        "email",  email,
        "picture", picture
      )
      @id
    end
```

Im having issues creating a form, I want to be able to access the profile page either by signing in with FB or by filling out the form. 
When I summit the form i want to be able to display the comments, the video and the photo you post on it. I haven't been able to figure out how to do this without breaking it. 
Ps. I just pushed the files to the repo. 
Thanks

**Comment by phlco** [comment]
:clap:

**Comment by andresv2** [comment]
One problem is my facebook login works for me, but if someone else tries to login they get the following error 

```
App Not Setup: The developers of this app have not set up this app properly for Facebook Login.
```

**Comment by vanderhoop** [comment]
Did you sign out of your account first?

**Comment by andresv2** [comment]
phil was able to help me!  
thanks
